import express from "express";
import path from "path";
import cors from "cors";
import Razorpay from "razorpay";
import dotenv from "dotenv";
import nodemailer from "nodemailer";
import { createServer as createViteServer } from "vite";
import { createClient } from "@supabase/supabase-js";
import { ShiprocketService } from "./src/services/shiprocketService.js";

dotenv.config();

// In-memory fallback state
let orders: any[] = [];
let inventory: Record<string, boolean> = {}; // { productId: isSoldOut }

// Supabase client initialization (server-side)
const supabaseUrl =
  process.env.VITE_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  "https://sqkdwltnkgjbylwykbsb.supabase.co";

const supabaseKey =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.VITE_SUPABASE_ANON_KEY ||
  process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa2R3bHRua2dqYnlsd3lrYnNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODkwMzg4MTEsImV4cCI6MjEwNDYxNDgxMX0.8uYJ8KDXN1wikXv2oOwMcgEUI4LcVjRjiVeN2Bxnasc";

const supabase = createClient(supabaseUrl, supabaseKey);

async function startServer() {
  const app = express();
  const PORT = 3000;

  // Middleware
  app.use(cors());
  app.use(express.json());

  // Inventory API
  app.get("/api/inventory", (req, res) => {
    res.json(inventory);
  });

  app.post("/api/inventory", (req, res) => {
    const { productId, isSoldOut } = req.body;
    inventory[productId] = isSoldOut;
    res.json({ success: true, inventory });
  });

  // Orders API (fetches from Supabase with in-memory fallback)
  app.get("/api/orders", async (req, res) => {
    try {
      const { data, error } = await supabase
        .from("orders")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) {
        console.warn("[Supabase] Orders fetch error, falling back to in-memory:", error.message);
        return res.json(orders);
      }

      // Format records to match frontend expectations
      const formatted = (data || []).map((row: any) => ({
        id: row.id,
        paymentId: row.payment_id,
        paymentGateway: row.payment_gateway,
        amount: row.amount,
        email: row.email,
        shippingDetails: row.shipping_details,
        items: row.items || [],
        status: row.status || "Processing",
        date: row.created_at,
        shiprocketOrderId: row.shiprocket_order_id,
        shiprocketShipmentId: row.shiprocket_shipment_id,
        awbCode: row.awb_code,
        courierName: row.courier_name,
        pickupStatus: row.pickup_status,
        pickupScheduledDate: row.pickup_scheduled_date,
        trackingUrl: row.tracking_url,
      }));

      // Combine with any memory-only orders not in DB
      const dbIds = new Set(formatted.map((o: any) => o.id));
      const memoryOnly = orders.filter((o) => !dbIds.has(o.id));
      res.json([...formatted, ...memoryOnly]);
    } catch (err: any) {
      console.error("[Orders] Error:", err);
      res.json(orders);
    }
  });

  // Live order tracking API
  app.get("/api/track-order/:orderId", async (req, res) => {
    try {
      const { orderId } = req.params;

      // 1. Fetch order details from Supabase or memory
      let order: any = null;
      try {
        const { data } = await supabase
          .from("orders")
          .select("*")
          .eq("id", orderId)
          .single();
        order = data;
      } catch (e) {
        // ignore
      }

      if (!order) {
        order = orders.find((o) => o.id === orderId);
      }

      if (!order) {
        return res.status(404).json({ error: "Order not found" });
      }

      const awbCode = order.awb_code || order.awbCode;
      const shipmentId = order.shiprocket_shipment_id || order.shiprocketShipmentId;

      if (!awbCode && !shipmentId) {
        return res.json({
          success: true,
          status: order.status || "Processing",
          message: "Shipment AWB is being generated by our warehouse.",
          order,
        });
      }

      // Query live tracking from Shiprocket
      const liveTracking = await ShiprocketService.trackShipment({
        awbCode,
        shipmentId,
      });

      res.json({
        success: true,
        orderId,
        awbCode,
        courierName: order.courier_name || order.courierName,
        trackingUrl: order.tracking_url || order.trackingUrl || (awbCode ? `https://shiprocket.co/tracking/${awbCode}` : null),
        liveTracking: liveTracking.tracking || null,
        status: order.status || "Processing",
      });
    } catch (error: any) {
      console.error("[Tracking Error]:", error);
      res.status(500).json({ error: error.message || "Failed to track order" });
    }
  });

  // Admin retry Shiprocket generation for an order
  app.post("/api/admin/shiprocket-retry/:orderId", async (req, res) => {
    try {
      const { orderId } = req.params;

      // Find order
      let order: any = null;
      try {
        const { data } = await supabase
          .from("orders")
          .select("*")
          .eq("id", orderId)
          .single();
        order = data;
      } catch (e) {
        // ignore
      }

      if (!order) {
        order = orders.find((o) => o.id === orderId);
      }

      if (!order) {
        return res.status(404).json({ error: "Order not found" });
      }

      const shippingDetails = order.shipping_details || order.shippingDetails;
      const items = order.items || [];
      const amount = order.amount;
      const email = order.email;

      console.log(`[Admin] Retrying Shiprocket fulfillment for order ${orderId}...`);
      const shiprocketResult = await ShiprocketService.fulfillOrder({
        orderId,
        amount,
        email,
        shippingDetails,
        items,
      });

      if (!shiprocketResult.success) {
        return res.status(400).json({
          error: "Shiprocket fulfillment retry failed",
          details: shiprocketResult,
        });
      }

      // Update Supabase
      try {
        await supabase
          .from("orders")
          .update({
            shiprocket_order_id: shiprocketResult.shiprocketOrderId,
            shiprocket_shipment_id: shiprocketResult.shiprocketShipmentId,
            awb_code: shiprocketResult.awbCode,
            courier_name: shiprocketResult.courierName,
            pickup_status: shiprocketResult.pickupStatus,
            pickup_scheduled_date: shiprocketResult.pickupScheduledDate,
            tracking_url: shiprocketResult.trackingUrl,
            status: shiprocketResult.awbCode ? "Shipped" : "Processing",
            updated_at: new Date().toISOString(),
          })
          .eq("id", orderId);
      } catch (dbErr) {
        console.warn("[Supabase] Update failed on retry:", dbErr);
      }

      // Update memory
      const memOrder = orders.find((o) => o.id === orderId);
      if (memOrder) {
        memOrder.shiprocketOrderId = shiprocketResult.shiprocketOrderId;
        memOrder.shiprocketShipmentId = shiprocketResult.shiprocketShipmentId;
        memOrder.awbCode = shiprocketResult.awbCode;
        memOrder.courierName = shiprocketResult.courierName;
        memOrder.trackingUrl = shiprocketResult.trackingUrl;
      }

      res.json({ success: true, shiprocket: shiprocketResult });
    } catch (error: any) {
      console.error("[Admin Retry Error]:", error);
      res.status(500).json({ error: error.message || "Failed to retry Shiprocket fulfillment" });
    }
  });

  // Razorpay API Routes
  app.post("/api/create-razorpay-order", async (req, res) => {
    try {
      const { amount } = req.body;
      const key_id = process.env.RAZORPAY_KEY_ID;
      const key_secret = process.env.RAZORPAY_KEY_SECRET;

      if (!key_id || !key_secret) {
        return res.status(500).json({
          error: "Razorpay credentials are not configured. Please add RAZORPAY_KEY_ID and RAZORPAY_KEY_SECRET.",
        });
      }

      const instance = new Razorpay({
        key_id,
        key_secret,
      });

      const options = {
        amount: Math.round(amount * 100), // amount in smallest currency unit (paise)
        currency: "INR",
        receipt: `receipt_order_${Date.now()}`,
      };

      const order = await instance.orders.create(options);

      res.json({
        id: order.id,
        currency: order.currency,
        amount: order.amount,
        key_id,
      });
    } catch (error: any) {
      console.error("Razorpay Error:", error);
      res.status(500).json({ error: error.message || "Failed to create order" });
    }
  });

  // Cashfree API Routes
  app.post("/api/create-cashfree-order", async (req, res) => {
    try {
      const { amount, customerName, customerEmail, customerPhone } = req.body;
      const appId = process.env.CASHFREE_APP_ID;
      const secretKey = process.env.CASHFREE_SECRET_KEY;
      const env = process.env.CASHFREE_ENV || "TEST";

      if (!appId || !secretKey) {
        return res.status(500).json({
          error: "Cashfree credentials are not configured. Please add CASHFREE_APP_ID and CASHFREE_SECRET_KEY in .env.",
        });
      }

      const isProduction = env.toUpperCase() === "PRODUCTION" || env.toUpperCase() === "PROD";
      const baseUrl = isProduction
        ? "https://api.cashfree.com/pg/orders"
        : "https://sandbox.cashfree.com/pg/orders";

      let phone = (customerPhone || "9999999999").replace(/\D/g, "");
      if (phone.length < 10) phone = "9999999999";
      if (phone.length > 10) phone = phone.slice(-10);

      const orderId = `order_${Date.now()}`;
      const payload = {
        order_id: orderId,
        order_amount: Number(amount),
        order_currency: "INR",
        customer_details: {
          customer_id: `cust_${Date.now()}`,
          customer_name: customerName || "Customer",
          customer_email: customerEmail || "customer@example.com",
          customer_phone: phone,
        },
      };

      const response = await fetch(baseUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-client-id": appId,
          "x-client-secret": secretKey,
          "x-api-version": "2023-08-01",
        },
        body: JSON.stringify(payload),
      });

      const data: any = await response.json();

      if (!response.ok) {
        console.error("Cashfree Order Creation Failed:", data);
        return res.status(response.status).json({
          error: data.message || "Failed to create Cashfree order",
        });
      }

      res.json({
        payment_session_id: data.payment_session_id,
        order_id: data.order_id,
        environment: isProduction ? "production" : "sandbox",
      });
    } catch (error: any) {
      console.error("Cashfree Error:", error);
      res.status(500).json({ error: error.message || "Failed to create Cashfree order" });
    }
  });

  // Single Integration Point: Confirm Payment & Automate Shiprocket Fulfillment
  app.post("/api/confirm-payment", async (req, res) => {
    try {
      const {
        paymentId,
        paymentGateway = "Razorpay",
        shippingDetails,
        amount,
        email,
        items = [],
      } = req.body;

      const orderId = `ord_${Date.now()}`;
      console.log(`[Order Confirmation] Processing order: ${orderId} (${paymentGateway}, PayID: ${paymentId})`);

      // 1. Trigger Shiprocket Fulfillment Pipeline
      let shiprocketData: any = null;
      try {
        console.log(`[Order Confirmation] Triggering Shiprocket for order: ${orderId}...`);
        shiprocketData = await ShiprocketService.fulfillOrder({
          orderId,
          amount,
          email,
          shippingDetails,
          items,
        });
        console.log(`[Order Confirmation] Shiprocket response:`, shiprocketData);
      } catch (srErr) {
        console.error("[Order Confirmation] Shiprocket fulfillment error (non-fatal):", srErr);
      }

      const awbCode = shiprocketData?.awbCode || null;
      const courierName = shiprocketData?.courierName || null;
      const shiprocketOrderId = shiprocketData?.shiprocketOrderId || null;
      const shiprocketShipmentId = shiprocketData?.shiprocketShipmentId || null;
      const pickupStatus = shiprocketData?.pickupStatus || null;
      const pickupScheduledDate = shiprocketData?.pickupScheduledDate || null;
      const trackingUrl = shiprocketData?.trackingUrl || (awbCode ? `https://shiprocket.co/tracking/${awbCode}` : null);

      // 2. Persist in Supabase PostgreSQL
      const dbOrderRecord = {
        id: orderId,
        payment_id: paymentId,
        payment_gateway: paymentGateway,
        amount: Number(amount),
        email: email,
        shipping_details: shippingDetails,
        items: items,
        status: awbCode ? "Shipped" : "Processing",
        shiprocket_order_id: shiprocketOrderId,
        shiprocket_shipment_id: shiprocketShipmentId,
        awb_code: awbCode,
        courier_name: courierName,
        pickup_status: pickupStatus,
        pickup_scheduled_date: pickupScheduledDate,
        tracking_url: trackingUrl,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
      };

      try {
        const { error: dbError } = await supabase.from("orders").insert([dbOrderRecord]);
        if (dbError) {
          console.warn("[Supabase] Insert order warning (ensure 'orders' table exists):", dbError.message);
        } else {
          console.log(`[Supabase] Order ${orderId} successfully saved to PostgreSQL.`);
        }
      } catch (dbEx) {
        console.warn("[Supabase] Exception writing to database:", dbEx);
      }

      // 3. Fallback in-memory state
      const newOrder = {
        id: orderId,
        paymentId,
        paymentGateway,
        amount,
        email,
        shippingDetails,
        items,
        date: new Date().toISOString(),
        status: awbCode ? "Shipped" : "Processing",
        shiprocketOrderId,
        shiprocketShipmentId,
        awbCode,
        courierName,
        pickupStatus,
        pickupScheduledDate,
        trackingUrl,
      };
      orders.unshift(newOrder);

      // 4. Send confirmation email with shipment details
      const smtpPass = process.env.RESEND_API_KEY || process.env.SMTP_PASSWORD;
      if (smtpPass) {
        try {
          const transporter = nodemailer.createTransport({
            host: "smtp.resend.com",
            port: 465,
            secure: true,
            auth: {
              user: "resend",
              pass: smtpPass,
            },
          });

          const trackingSection = awbCode
            ? `
            <div style="background: #E8F5E9; border: 1px solid #A5D6A7; padding: 15px; border-radius: 8px; margin: 20px 0;">
              <h3 style="margin-top: 0; color: #2E7D32;">Shipment & Tracking Information</h3>
              <p><strong>Courier:</strong> ${courierName || "Shiprocket Express"}</p>
              <p><strong>AWB / Tracking Number:</strong> ${awbCode}</p>
              <p><a href="${trackingUrl}" style="background: #2E7D32; color: #ffffff; padding: 8px 16px; text-decoration: none; border-radius: 4px; display: inline-block; font-weight: bold; margin-top: 8px;">Track Your Shipment</a></p>
            </div>
            `
            : `
            <p style="font-size: 14px; color: #555;">
              Our logistics partner (Shiprocket) is preparing your shipment. You will receive live tracking updates once the courier is dispatched.
            </p>
            `;

          await transporter.sendMail({
            from: "onboarding@resend.dev",
            to: email,
            subject: `Order Confirmation #${orderId} - QICDOCK`,
            html: `
              <div style="font-family: sans-serif; color: #0A1E3F; max-width: 600px; margin: 0 auto; padding: 20px;">
                <h1 style="color: #0A1E3F;">Thank you for your order!</h1>
                <p>Your payment was successful and your order has been dispatched to fulfillment.</p>
                
                <div style="background: #FAF7F0; padding: 15px; border-radius: 8px; margin: 20px 0;">
                  <h3 style="margin-top: 0;">Order Summary</h3>
                  <p><strong>Order ID:</strong> ${orderId}</p>
                  <p><strong>Payment Method:</strong> ${paymentGateway}</p>
                  <p><strong>Payment ID:</strong> ${paymentId}</p>
                  <p><strong>Amount Paid:</strong> ₹${amount}</p>
                </div>

                ${trackingSection}

                <div style="background: #FAF7F0; padding: 15px; border-radius: 8px; margin: 20px 0;">
                  <h3 style="margin-top: 0;">Shipping To:</h3>
                  <p>${shippingDetails.name}<br/>
                  ${shippingDetails.addressLine}<br/>
                  ${shippingDetails.state}, ${shippingDetails.pincode}<br/>
                  ${shippingDetails.country || "India"}<br/>
                  Phone: ${shippingDetails.phone}</p>
                </div>

                <p style="font-size: 16px; font-weight: bold; color: #22C55E;">
                  Estimated delivery in 3-5 business days.
                </p>
              </div>
            `,
          });
        } catch (mailErr) {
          console.error("Failed to send email confirmation:", mailErr);
        }
      }

      res.json({
        success: true,
        order: newOrder,
        shiprocket: shiprocketData,
      });
    } catch (error: any) {
      console.error("Confirmation Error:", error);
      res.status(500).json({ error: error.message || "Failed to confirm payment" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
